services:
#este contenedor soluciona el cambio de ip publica
#cuando se reinicia el router por ejemplo
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host # Para que detecte bien la IP externa
    environment:
      SUBDOMAINS: ${MI_SUBDOMINIO}
      TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: false
    restart: unless-stopped
  # EL PROXY Nginx Proxy Manager
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-asir
    restart: always
    ports:
      - "80:80"    # HTTP para renovar certificados
      - "4443:443"  # HTTPS LDAPS y Nextcloud
      - "81:81"    # administración del Proxy
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - red-publica
      - red-privada

  # OPENLDAP
  ldap:
    image: osixia/openldap:latest
    container_name: ldap-servidor
    restart: always
    environment:
      LDAP_ORGANISATION: "${LDAP_ORGANISATION}"
      LDAP_DOMAIN: "${MI_DOMINIO}"
      LDAP_ADMIN_PASSWORD: "${CLAVE_ADMIN_LDAP}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASS}"
      LDAP_TLS: "true"
    networks:
      - red-privada
    volumes:
      - ./ldap/var:/var/lib/ldap
      - ./ldap/etc:/etc/ldap/slapd.d

  # PHP PARA GESTIONAR LDAP
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-servidor"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
      - red-privada
      - red-publica
    depends_on:
      - ldap
# BASE DE DATOS NEXTCLOUD
  db-nextcloud:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${NC_DB_ROOT_PASS}"
      MYSQL_DATABASE: "${NC_DB_NAME}"
      MYSQL_USER: "${NC_DB_USER}"
      MYSQL_PASSWORD: "${NC_DB_PASS}"
    volumes:
      - ./nextcloud_db:/var/lib/mysql
    networks:
      - red-privada

  # NEXTCLOUD
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-asir
    restart: always
    depends_on:
      - db-nextcloud
      - ldap
    environment:
      MYSQL_HOST: "db-nextcloud"
      MYSQL_DATABASE: "${NC_DB_NAME}"
      MYSQL_USER: "${NC_DB_USER}"
      MYSQL_PASSWORD: "${NC_DB_PASS}"
    volumes:
      - ./nextcloud_data:/var/www/html
    networks:
      - red-privada
      - red-publica # Necesita pública para que el Proxy llegue a él

  wazuh-agent:
    image: wazuh/wazuh-agent:4.14.3
    container_name: wazuh-agente-asir
    environment:
      - WAZUH_MANAGER=wazuh-manager # Gracias a la red externa, lo encontrará por nombre
    volumes:
      - ./nextcloud_data/data/nextcloud.log:/var/log/nextcloud/nextcloud.log:ro
    networks:
      - red-seguridad # <--- Conexión al SIEM
      - red-privada   # <--- Conexión a Nextcloud
    depends_on:
      - nextcloud
# REDES
networks:
  red-publica:
    driver: bridge
  red-privada:
    driver: bridge
    internal: true
  red-seguridad:
    external: true
