services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      SUBDOMAINS: ${MI_SUBDOMINIO}
      TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: "false"
    restart: unless-stopped

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-asir
    restart: always
    ports:
      - "80:80"
      - "4443:443"
      - "81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - red-publica
      #comento esta linea porque no parece necesaria
      #- red-privada 

  ldap:
    image: osixia/openldap:latest
    container_name: ldap-servidor
    restart: always
    environment:
      LDAP_ORGANISATION: "${LDAP_ORGANISATION}"
      LDAP_DOMAIN: "${MI_DOMINIO}"
      LDAP_ADMIN_PASSWORD: "${CLAVE_ADMIN_LDAP}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASS}"
      LDAP_TLS: "true"
    networks:
      - red-privada
    volumes:
      - ldap_var:/var/lib/ldap
      - ldap_etc:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-servidor"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
      - red-privada
      - red-publica
    depends_on:
      - ldap

  db-nextcloud:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${NC_DB_ROOT_PASS}"
      MYSQL_DATABASE: "${NC_DB_NAME}"
      MYSQL_USER: "${NC_DB_USER}"
      MYSQL_PASSWORD: "${NC_DB_PASS}"
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - red-privada

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-asir
    restart: always
    depends_on:
      - db-nextcloud
      - ldap
    environment:
      MYSQL_HOST: "db-nextcloud"
      MYSQL_DATABASE: "${NC_DB_NAME}"
      MYSQL_USER: "${NC_DB_USER}"
      MYSQL_PASSWORD: "${NC_DB_PASS}"
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - red-privada
      - red-publica

  wazuh-agent:
    image: wazuh/wazuh-agent:4.14.3
    container_name: wazuh-agente-asir
    environment:
      - WAZUH_MANAGER=wazuh-manager
    volumes:
      # Mantenemos este como ruta relativa para que el agente lea el log local si existe
      - ./nextcloud_data/data/nextcloud.log:/var/log/nextcloud/nextcloud.log:ro
    networks:
      - red-seguridad
      - red-privada
    depends_on:
      - nextcloud

# DEFINICIÓN DE LOS NUEVOS VOLÚMENES
volumes:
  npm_data:
  npm_letsencrypt:
  ldap_var:
  ldap_etc:
  nextcloud_db:
  nextcloud_data:

networks:
  red-publica:
    driver: bridge
  red-privada:
    driver: bridge
    internal: true
  red-seguridad:
    external: true
